version: "3"

services:
  db:
    image: postgres:11.5
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db:
