default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: presentation_builder_development
test:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: presentation_builder_test
production:
  <<: *default
  url: <%= ENV['PROD_DATABASE_URL'] %>
